language: ruby
services:
  - postgresql
rvm:
  - 2.3.1
env:
  - DB=sqlite
  - DB=postgresql
script: 
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database electune_test;' -U postgres
bundler_args: --binstubs=./bundler_stubs --without development
