sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql2: &mysql2
  adapter: mysql2
  username: travis
  password:
  database: electune_<%= Rails.env %>
  encoding: utf8

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: electune_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "sqlite" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
