# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5754e36ec76aa7765187c60acbd9ab8e4cf22027d9b5295439be3d4cfe0054b1fdb41e7368026d9e87558ddbc1913822f30a2218cef0a6f21ee3c78f3310e0ab

test:
  secret_key_base: 9c131f8dcd6bd8f3214b4fbcc2f1c3b97f3a32e51eb16d49463a8a81e9019021de42792cfa6cfb1b30499e502526e0ddc00c2978a19e4a454977673e2b960682

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
